### ISSUE TITLE
Support for import statements in karma tests?

### ISSUE THREAD

**Issue by starsinmypockets** [mvader/react-es6-webpack-karma-boilerplate#3]
Any idea how to support import statements in test specs? I'm tryin to implement something along the lines of:

``` javascript
import '../src/modules/module.js' as Foo;

describe('1+1', () => {
  let sum = 1+1;

  it('should be 2', () => {
    expect(2).toBe(2);
  });

  it('should be Foo', () => {
    expect(Foo).toBe('Foo');
  });
});
```

**Comment by AdamMcCormick** [comment]
You need to use babel as a preprocessor for your tests in your karma config. Have a look at https://github.com/babel/karma-babel-preprocessor
